# Generated by Django 4.2.2 on 2023-06-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='Finish date is greater than start date',
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('finish_date__gt', models.F('start_date'))), name='Finish date has to be greater than start date'),
        ),
    ]
